services:

    postgres:
      image: bitnami/postgresql:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRESQL_USER: helton
        POSTGRESQL_PASSWORD: admin
        POSTGRESQL_DATABASE: socialmedia

      volumes:
        - fastapi_pg_data:/bitnami/postgresql

volumes:
  fastapi_pg_data:

#Acessar DB psql -h localhost -U myuser -d mydatabase